// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaOBY6iFMLXhsiuCb-cRPAHh6hfC3atJg',
    appId: '1:866148282057:web:06ac47e982a6dbd814a718',
    messagingSenderId: '866148282057',
    projectId: 'coder-s-cup-minigames',
    authDomain: 'coder-s-cup-minigames.firebaseapp.com',
    storageBucket: 'coder-s-cup-minigames.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXXiX9M-pHN6p3spzSbnEZ6uM-2gPm5Q',
    appId: '1:866148282057:android:734ed6c02a0b1c3a14a718',
    messagingSenderId: '866148282057',
    projectId: 'coder-s-cup-minigames',
    storageBucket: 'coder-s-cup-minigames.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4cL46-UjcSRNEFzaVkaVIcQqnFclemQ',
    appId: '1:866148282057:ios:38f9089138a8cbb414a718',
    messagingSenderId: '866148282057',
    projectId: 'coder-s-cup-minigames',
    storageBucket: 'coder-s-cup-minigames.firebasestorage.app',
    iosClientId: '866148282057-263dmjjuqkcqdj1be2mv7st0b96kjikq.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmActivityComicGameAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU4cL46-UjcSRNEFzaVkaVIcQqnFclemQ',
    appId: '1:866148282057:ios:38f9089138a8cbb414a718',
    messagingSenderId: '866148282057',
    projectId: 'coder-s-cup-minigames',
    storageBucket: 'coder-s-cup-minigames.firebasestorage.app',
    iosClientId: '866148282057-263dmjjuqkcqdj1be2mv7st0b96kjikq.apps.googleusercontent.com',
    iosBundleId: 'com.example.acmActivityComicGameAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaOBY6iFMLXhsiuCb-cRPAHh6hfC3atJg',
    appId: '1:866148282057:web:1d4e3efc16152cfb14a718',
    messagingSenderId: '866148282057',
    projectId: 'coder-s-cup-minigames',
    authDomain: 'coder-s-cup-minigames.firebaseapp.com',
    storageBucket: 'coder-s-cup-minigames.firebasestorage.app',
  );
}
